Annotation3D: fix NoSuchMethodError when attempting to close Context
- since NoSuchMethodError extends Throwable instead of Exception, it was not being caught